#!/bin/bash
#
# Description:  This shell script takes care of starting and stopping mem_watcher
# Yao Xudong, Aug. 2nd, 2019
#
# Source function library
. /etc/init.d/functions

SNAME=mem_watcher

#the full path and name of the daemon program
#Warning: The name of executable file must be identical with service name
#PROG=/opt/mem_watcher/python/run_memory_watcher.sh
PROG=/home/yaoxudong/tools_memory_watch/src/python/run_memory_watcher.sh

# start function
start() {
    #check the daemon status first
    #if [ -f /var/lock/subsys/$SNAME ]
    #then
    #    echo "$SNAME is already started!"
    #    exit 0;
    #else
    #    action "Starting $SNAME ..." $PROG
    #    [ $? -eq 0 ] && touch 
    #    exit 0;
    #fi
        echo "$SNAME is starting"
        action "Starting $SNAME ..." $PROG
        [ $? -eq 0 ] && PROG
        exit 0;
}

#stop function
stop() {
    echo "Stopping $SNAME ..."
    killproc $SNAME
}

case "$1" in
start)
  start
  ;;
stop)
  stop
  ;;
reload|restart)
  stop
  start
  ;;
status)
  status $SNAME
  ;;
*)
  echo $"Usage: $0 {start|stop|restart|status}"
  exit 1
esac
